dojo task 2 done
maxkenkomoda/kintone_dojo pull request #2
Opened 2022-06-28 05:59 UTC by maxkenkomoda

@tomoe-sanuki 
お疲れさまです。お忙しい中大変申し訳無いのですが、お時間ある際に課題のレビューをお願い致します！！

## 課題の条件
1. オブジェクトを作成し、consoleに出力する
2. 1で作成したオブジェクトをHTMLのテーブルに出力する
3. さらにリスト表示も行う

## 結果 
### 1. オブジェクトを作成し、consoleに出力する
- できました。[ソースコードの位置](https://github.com/maxkenkomoda/kintone_dojo/blob/task_2/2-JS/task3.html#L96-L120)

### 2. 1で作成したオブジェクトをHTMLのテーブルに出力する
- 表示できました。[ソースコードの位置](https://github.com/maxkenkomoda/kintone_dojo/blob/task_2/2-JS/task3.html#L123-L159)
- 2重ループになっているところはもう少し良い実装がある気がしますが、一旦これで提出します。。。。

### 3. さらにリスト表示も行う
- 表示できました。[ソースコードの位置](https://github.com/maxkenkomoda/kintone_dojo/blob/task_2/2-JS/task3.html#L160-L186)

## スクリーンショット
![image](https://user-images.githubusercontent.com/58941838/176102827-4b32716a-1a3b-49f7-a3d5-a4affa5fec94.png)

2022-06-29 09:46 UTC, tomoe-sanuki requested changes
以下ご確認お願いいたします🙇‍♀️

・Object.keys(fileManage)に対してforEachを回すとその中でObject.keys(fileManage[val]).forEach((v)ができるので、entriesよりkeysの方が良いかと思います。
・閲覧権限がeveryoneのものはObject.keys(fileManage)の中で判定できるので、上記の中に入れ込めばさらにコードが短くなります。

2022-06-30 00:44 UTC, maxkenkomoda commented on 2-JS/task3.html
> +      });
シンプルな処理に変更
Objectかどうかの判定も今回不必要だと思ったので消去

2022-06-30 00:45 UTC, maxkenkomoda commented on 2-JS/task3.html
> +      };
課題③用の部分は関数として切り出し

2022-06-30 00:47 UTC, maxkenkomoda commented
@tomoe-sanuki 

修正しました。
https://github.com/maxkenkomoda/kintone_dojo/pull/2#discussion_r910514415
https://github.com/maxkenkomoda/kintone_dojo/pull/2#discussion_r910514565

お忙しい中申し訳ないのですが、お時間ある際に再度レビューをお願いいたします🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️

2022-06-30 05:28 UTC, tomoe-sanuki approved these changes
ご修正ありがとうございます！OKです！

2022-06-30 05:28 UTC, merged