Intermediate task
maxkenkomoda/kintone_dojo pull request #4
Opened 2022-07-01 01:44 UTC by maxkenkomoda

@tomoe-sanuki 
お疲れさまです。お忙しい中大変申し訳無いのですが、お時間ある際に課題のレビューをお願い致します！！🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️

# 中間課題

## 要件
- 日付/カテゴリー/タイトルが一覧形式で表示されること
-> 実装しました。

- カテゴリーごとに色分けがされること
-> 実装しました。色のセンスはないですが。。。

- タイトルをクリックすると、リンク先のURLに遷移すること
-> 実装しました。

- 表示するニュースが増減しても、問題なく動作すること、デザインが崩れないこと。
-> 実装しました。

プラスαとして
- 表示するニュースを自動的に最新順に並び替えること
-> 最初にページを表示するときは最新順で表示されるようにしてあります。

- タイトル文字数が30を超えるときは表示制限を行う
-> 実装しました。

- 記事の最大表示数を3に制限すること
-> こちらは実装してないです。代わりに制限ではなく、最新順か古い順、何件表示するかを選択リストとして表示し、ユーザーが選択すると表も変化するように勝手に実装しました。(駄目だったらすみません！)

![d1cd609d542cca227775568b6adc078c](https://user-images.githubusercontent.com/58941838/176805921-72381b17-7c9b-4018-aa44-3c76846dcdec.gif)

追加で軽くレスポンシブ対応しました。

![a3898b60f605185a893d799426cc1aa0](https://user-images.githubusercontent.com/58941838/176805956-44376d48-8463-4f35-bd20-50d8a27b56d3.gif)

2022-07-04 04:57 UTC, tomoe-sanuki requested changes
お疲れさまでした！
最新順/古い順、何件表示するかを選択できるようにしてくださったの素晴らしいですね✨
デザインもバッチリです！

一点だけ、innerHTMLの部分、
innerHTML += ` ` で生成していただくとよりコードを簡潔にできるかと思います…！

ご検討のほどよろしくお願いいたします🙇‍♀️

2022-07-04 07:41 UTC, maxkenkomoda commented on 中間課題/index.js
> +      }" class="content">${truncateSentence(newsData.content.value)}</a></td>`;
`element.innterHTML +=`に変更しました。
ついでに1行なら関数にする必要ないかなと思い、関数も全部削除しました。
コードのダイエット化成功しました。

2022-07-04 07:44 UTC, maxkenkomoda commented
@tomoe-sanuki 

お疲れさまです！お忙しい中レビューをして頂き誠にありがとうございます。
ChangeRequestに従い修正しました。

https://github.com/maxkenkomoda/kintone_dojo/pull/4/files#r912714301

`element.innerHTML +=`知りませんでした。。。

またお時間ある際にレビューをお願いします。🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️

2022-07-06 05:56 UTC, tomoe-sanuki commented on 中間課題/index.js
> +      }" class="content">${truncateSentence(newsData.content.value)}</a></td>`;
ご修正ありがとうございます！
もう一歩、L46～59をひとつの `element.innterHTML +=` 内で書いていただくと
もっともっとダイエット化できると思いますのでご確認ください🙏

2022-07-06 05:56 UTC, tomoe-sanuki requested changes
お疲れさまです！
一点以前のレビューのやりとりにコメント追加いたしましたので
ご確認お願いいたします！

2022-07-06 07:46 UTC, maxkenkomoda commented on 中間課題/index.js
> +      </td>`;
ひとつの`innerHTML +=`で処理ができるように変更

2022-07-06 07:47 UTC, maxkenkomoda commented on 中間課題/index.js
> +      }" class="content">${truncateSentence(newsData.content.value)}</a></td>`;
修正しました！
https://github.com/maxkenkomoda/kintone_dojo/pull/4#discussion_r914521247

2022-07-06 07:48 UTC, maxkenkomoda commented
@tomoe-sanuki 

お疲れさまです！お忙しい中再度レビューをして頂き誠にありがとうございます。
ChangeRequestに従い修正しました。

https://github.com/maxkenkomoda/kintone_dojo/pull/4#discussion_r914521247
よくよく考えたら一つの`innerHTML +=`でできましたね。。。。恥ずかしいです。

またお時間ある際にレビューをお願いします。🙇‍♀️🙇‍♀️🙇‍♀️🙇‍♀️

2022-07-08 00:38 UTC, tomoe-sanuki approved these changes
こちらOKです～！お疲れさまでした！

2022-07-08 00:38 UTC, merged