課題8 JS REST API
maxkenkomoda/kintone_dojo pull request #7
Opened 2022-07-05 06:00 UTC by maxkenkomoda

@tomoe-sanuki  
お疲れさまです。お忙しい中大変申し訳無いのですが、お時間ある際に課題のレビューをお願い致します！！🙇‍♀️🙇‍♀️🙇‍♀️

# 課題
REST APIでフォーム情報を取得し、レコード登録画面を開くとドロップダウンに設定された値が過不足なく、設定順に表示されること
## 結果
・実装しました。
![e49493f48b903e991a09e9070326afc4](https://user-images.githubusercontent.com/58941838/177259378-2068f5f6-8812-4133-97be-8960e5820c30.gif)

2022-07-06 05:41 UTC, tomoe-sanuki commented on JS-REST-API-1/js-rest-api-1.js
> +    const params = { app: 21 };
アプリIDを指定していただいているのですが、
kintone.app.getId() で現在開いているアプリのIDを取得できますので、こちらをお使いいただければと思います！
https://developer.cybozu.io/hc/ja/articles/202166300

2022-07-06 05:52 UTC, tomoe-sanuki requested changes
お疲れさまです！
一点だけコメント追加いたしましたのでご確認お願いいたします🙇‍♀️

2022-07-06 08:04 UTC, maxkenkomoda commented on JS-REST-API-1/js-rest-api-1.js
> +    const params = { app: appId };
アプリIDをハードコードから関数経由で取得するように変更

2022-07-06 08:06 UTC, maxkenkomoda commented
@tomoe-sanuki 

お忙しい中レビューして頂き誠にありがとうございます！

ご指摘頂いた点 、修正致しました。
https://github.com/maxkenkomoda/kintone_dojo/pull/7#discussion_r915556086

またお時間ある際にレビューお願いいたします🙇‍♀️

2022-07-07 07:36 UTC, maxkenkomoda commented on JS-REST-API-1/js-rest-api-1.js
> +    const params = { app: kintone.app.getId() };
アプリIDをハードコードから関数経由で取得するように変更

2022-07-08 00:35 UTC, tomoe-sanuki commented on JS-REST-API-1/js-rest-api-1.js
> +
index順に並び替えの部分について、Object.keys(options) の中身を見ていただくとindex があると思います。
そちらを使って処理いただくともっとスッキリするかと思いますので、ご確認お願いいたします🙏

2022-07-08 00:37 UTC, tomoe-sanuki requested changes
ご修正ありがとうございます！
五月雨式に指摘してしまい申し訳ございませんが、もう一点コメント追加いたしましたので
ご確認・ご対応の程よろしくお願いいたします🙇‍♀️

2022-07-08 01:45 UTC, maxkenkomoda commented on JS-REST-API-1/js-rest-api-1.js
> +        }
一度空の配列を用意し、REST APIから取得したindexを指定し作った配列にpushする処理に変更

2022-07-08 01:47 UTC, maxkenkomoda commented
@tomoe-sanuki 

お疲れ様です！
頂いた指摘を修正しました！
https://github.com/maxkenkomoda/kintone_dojo/pull/7#discussion_r916398177

お忙しい中大変申し訳無いのですが、またお時間ある際にレビューをお願いします。🙇‍♂️

2022-07-08 02:38 UTC, tomoe-sanuki commented on JS-REST-API-1/js-rest-api-1.js
> +        }
ご対応ありがとうございます！
そもそものindex使っていただいていましたね…レビューが誤っておりすみません🙇‍♀️
sortとindexをpushするやり方どっちがよいか確認いたしました！
sortでも誤っているわけではないのですが、やはり破壊的メソッドなので、後者推奨とのことでした！
よろしくお願いいたします🙏

2022-07-08 02:40 UTC, tomoe-sanuki approved these changes
OKです！お疲れさまでした🎉🎉🎉

2022-07-08 02:40 UTC, merged

2022-07-08 02:43 UTC, maxkenkomoda commented on JS-REST-API-1/js-rest-api-1.js
> +        }
ありがとうございます！
> sortでも誤っているわけではないのですが、やはり破壊的メソッドなので、後者推奨とのことでした！

納得しました！ありがとうございます！！！